### ISSUE TITLE
def load_state_dict(self, state_dict)

### ISSUE THREAD

**Issue by watershadow1212** [rezafuru/generalized-octave-convolution-compression#1]
Nice work!But I still can't run the update block.This is how we load the moudel
        model = net.from_state_dict(torch.load(checkpoint_path)["state_dict"])
        model = net.to('cuda')
        model.update(force=True)
        model = model.eval().cuda()
we changed this block
           def load_state_dict(self, state_dict):
        # Dynamically update the entropy bottleneck buffers related to the CDFs
        update_registered_buffers(
            self.entropy_bottleneck,
            "entropy_bottleneck",
            ["_quantized_cdf", "_offset", "_cdf_length"],
            state_dict,
        )
        super().load_state_dict(state_dict)
        
into 
              def load_state_dict(self, state_dict):
                  update_registered_buffers(
                      self.gaussian_conditional_h,
                      "gaussian_conditional_h",
                      ["_quantized_cdf", "_offset", "_cdf_length", "scale_table"],
                      state_dict,
                  )
                  update_registered_buffers(
                      self.gaussian_conditional_l,
                      "gaussian_conditional_l",
                      ["_quantized_cdf", "_offset", "_cdf_length", "scale_table"],
                      state_dict,
                  )
                  update_registered_buffers(
                      self.entropy_bottleneck.eb_l,
                      "entropy_bottleneck.eb_l",
                      ["_quantized_cdf", "_offset", "_cdf_length"],
                      state_dict,
                  )
                  update_registered_buffers(
                      self.entropy_bottleneck.eb_h,
                      "entropy_bottleneck.eb_h",
                      ["_quantized_cdf", "_offset", "_cdf_length"],
                      state_dict,
                  )
                  # super().load_state_dict(state_dict)
 
 Still not work,I wonder how you make it.Thanks a lot!!

**Comment by rezafuru** [comment]
Hi, could you please provide some more details on what you're trying to do? I'll gladly look into the problem, but I'll need to be able to reproduce your error and see the error messages.

In particular, since it seems like you're trying to load pretrained weights, I'd like to know whether you were able to successfully initialize and train the model. 

Best
rezafuru

**Comment by fishxdx** [comment]
> Hi, could you please provide some more details on what you're trying to do? I'll gladly look into the problem, but I'll need to be able to reproduce your error and see the error messages.
> 
> In particular, since it seems like you're trying to load pretrained weights, I'd like to know whether you were able to successfully initialize and train the model.
> 
> Best rezafuru

Hi,I'm more than glad to hear your reply.I'm sorry I've been busy with other things some time ago.I have successfully updated the dictionary, the code works fine, but in the part of the forword that contains the Hyprior network, I get a higher value than the initial image, which obviously does not coincide with the idea of compression. By the way, the training set of my images is applied to (8,128,128), and the testsets are (8,512,512) multispectral images. I wonder if you have encountered this situation. Thanks again for your reply.Here are my training codes.

    def __init__(self, n=192, m=192):
        super(ceshi, self).__init__(N=n, M=m)
        self.entropy_bottleneck_1 = HighLowEntropyBottleneck(entropy_bottleneck_channels=n)

        self.g_a = nn.Sequential(
            FirstOctave(out_channels=n),
            GeneralizedOctaveConv(in_channels=n,
                                  out_channels=n,
                                  kernel_size=5,
                                  stride=2),
            GeneralizedOctaveConv(in_channels=n,
                                  out_channels=n,
                                  kernel_size=5,
                                  stride=2),
            GeneralizedOctaveConv(in_channels=n,
                                  out_channels=m,
                                  kernel_size=5,
                                  stride=2)
        )

        self.g_s = nn.Sequential(
            GeneralizedOctaveTransposeConv(in_channels=m,
                                           out_channels=n,
                                           kernel_size=5,
                                           stride=2),
            GeneralizedOctaveTransposeConv(in_channels=n,
                                           out_channels=n,
                                           kernel_size=5,
                                           stride=2),
            GeneralizedOctaveTransposeConv(in_channels=n,
                                           out_channels=n,
                                           kernel_size=5,
                                           stride=2),
            LastOctave(in_channels=n,
                       kernel_size=5,
                       out_channels=8)
        )

        self.h_a = nn.Sequential(
            GeneralizedOctaveConv(in_channels=m,
                                  out_channels=m,
                                  kernel_size=5,
                                  stride=1),
            GeneralizedOctaveConv(in_channels=n,
                                  out_channels=n,
                                  kernel_size=5,
                                  stride=2),
            GeneralizedOctaveConv(in_channels=n,
                                  out_channels=n,
                                  kernel_size=5,
                                  stride=2)
        )
        self.h_s = nn.Sequential(
            GeneralizedOctaveTransposeConv(in_channels=n,
                                           out_channels=m,
                                           kernel_size=5,
                                           stride=2),
            GeneralizedOctaveTransposeConv(in_channels=m,
                                           out_channels=m * 3 // 2,
                                           kernel_size=5,
                                           stride=2),

            GeneralizedOctaveTransposeConv(in_channels=m * 3 // 2,
                                           out_channels=m,
                                           kernel_size=5,
                                           stride=1),
        )
        self.gaussian_conditional_h = GaussianConditional(None)
        self.gaussian_conditional_l = GaussianConditional(None)
        self.N = int(n)
        self.M = int(m)


    def forward(self, x):
        y_h, y_l = self.g_a(x)
        z_h_l = self.h_a((y_h, y_l))
        z_q_h, z_q_l, z_h_likelihoods, z_l_likelihoods = self.entropy_bottleneck_1(z_h_l)
        gaussian_params_h, gaussian_params_l = self.h_s((z_q_h, z_q_l))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        y_h_hat, y_h_likelihoods = self.gaussian_conditional_h(y_h, scales_h)
        y_l_hat, y_l_likelihoods = self.gaussian_conditional_l(y_l, scales_l)
        #
        x_hat = self.g_s((y_h_hat, y_l_hat))

        return {
            "x_hat": x_hat,
            "likelihoods": {"y_h": y_h_likelihoods, "y_l": y_l_likelihoods, "z_h": z_h_likelihoods, "z_l": z_l_likelihoods},
        }
        
      y_h_hat will get a highter value than 512*512 when run the y_h_hat, y_h_likelihoods = self.gaussian_conditional_h(y_h, scales_h).
      
      Best wishes

**Comment by fishxdx** [comment]
I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the code
    def compress(self, x):
        y_h, y_l = self.g_a(x)
        z_h, z_l = self.h_a((y_h, y_l))
        z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
        z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
        gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
        # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
        y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
        y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
        return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
                "shape": [z_h.size()[-2:], z_l.size()[-2:]]
                }


    def decompress(self, strings, shape):
        assert isinstance(strings, list) and len(strings) == 2
        assert isinstance(shape, list) and len(shape) == 2
        z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
        gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        strings_y_h, strings_y_l = strings[1]
        y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
        y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
        x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
        return {"x_hat": x_hat}

after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become biger than the initial image.
best wishes

**Comment by fishxdx** [comment]
I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the code

    def compress(self, x):
        y_h, y_l = self.g_a(x)
        z_h, z_l = self.h_a((y_h, y_l))
        z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
        z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
        gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
        # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
        y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
        y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
        return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
                "shape": [z_h.size()[-2:], z_l.size()[-2:]]
                }


    def decompress(self, strings, shape):
        assert isinstance(strings, list) and len(strings) == 2
        assert isinstance(shape, list) and len(shape) == 2
        z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
        gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        strings_y_h, strings_y_l = strings[1]
        y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
        y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
        x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
        return {"x_hat": x_hat}

after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become biger than the initial image.
best wishes

**Comment by fishxdx** [comment]
I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes
    def compress(self, x):
        y_h, y_l = self.g_a(x)
        z_h, z_l = self.h_a((y_h, y_l))
        z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
        z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
        gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
        # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
        y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
        y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
        return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
                "shape": [z_h.size()[-2:], z_l.size()[-2:]]
                }


    def decompress(self, strings, shape):
        assert isinstance(strings, list) and len(strings) == 2
        assert isinstance(shape, list) and len(shape) == 2
        z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
        gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        strings_y_h, strings_y_l = strings[1]
        y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
        y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
        x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
        return {"x_hat": x_hat}

after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image.
best wishes

**Comment by fishxdx** [comment]
I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes

    def compress(self, x):
        y_h, y_l = self.g_a(x)
        z_h, z_l = self.h_a((y_h, y_l))
        z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
        z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
        gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
        # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
        y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
        y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
        return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
                "shape": [z_h.size()[-2:], z_l.size()[-2:]]
                }


    def decompress(self, strings, shape):
        assert isinstance(strings, list) and len(strings) == 2
        assert isinstance(shape, list) and len(shape) == 2
        z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
        gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
        scales_h = gaussian_params_h
        scales_l = gaussian_params_l
        indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
        indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
        strings_y_h, strings_y_l = strings[1]
        y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
        y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
        x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
        return {"x_hat": x_hat}

after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image.
best wishes

**Comment by rezafuru** [comment]
> I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes
> 
> ```
> def compress(self, x):
>     y_h, y_l = self.g_a(x)
>     z_h, z_l = self.h_a((y_h, y_l))
>     z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
>     z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
>     gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
>     scales_h = gaussian_params_h
>     scales_l = gaussian_params_l
>     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
>     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
>     # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
>     # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
>     y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
>     y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
>     return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
>             "shape": [z_h.size()[-2:], z_l.size()[-2:]]
>             }
> 
> 
> def decompress(self, strings, shape):
>     assert isinstance(strings, list) and len(strings) == 2
>     assert isinstance(shape, list) and len(shape) == 2
>     z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
>     gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
>     scales_h = gaussian_params_h
>     scales_l = gaussian_params_l
>     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
>     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
>     strings_y_h, strings_y_l = strings[1]
>     y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
>     y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
>     x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
>     return {"x_hat": x_hat}
> ```
> 
> after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image. best wishes


Have you trained the compression models? I've not provided any weights, it isn't too unsurprising that the rate is higher for the compressed representation on a freshly initialized model

**Comment by fishxdx** [comment]
> > I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes
> > ```
> > def compress(self, x):
> >     y_h, y_l = self.g_a(x)
> >     z_h, z_l = self.h_a((y_h, y_l))
> >     z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
> >     z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
> >     gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
> >     scales_h = gaussian_params_h
> >     scales_l = gaussian_params_l
> >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> >     # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
> >     # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
> >     y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
> >     y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
> >     return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
> >             "shape": [z_h.size()[-2:], z_l.size()[-2:]]
> >             }
> > 
> > 
> > def decompress(self, strings, shape):
> >     assert isinstance(strings, list) and len(strings) == 2
> >     assert isinstance(shape, list) and len(shape) == 2
> >     z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
> >     gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
> >     scales_h = gaussian_params_h
> >     scales_l = gaussian_params_l
> >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> >     strings_y_h, strings_y_l = strings[1]
> >     y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
> >     y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
> >     x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
> >     return {"x_hat": x_hat}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image. best wishes
> 
> Have you trained the compression models? I've not provided any weights, it isn't too unsurprising that the rate is higher for the compressed representation on a freshly initialized model

I trained the model with my usual customary parameters, with a learning rate of 1e-4 for VAE and 1e-5 for lambada, and more than 300 rounds of training. The dataset is (8, 128, 128) multispectral images. Incidentally the training process looks all right and the loss can be reduced to single digits, but it is the compression bitrate that gets greater than 1 when testing, I was wondering if you have encountered this problem while training.

**Comment by rezafuru** [comment]
> > > I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes
> > > ```
> > > def compress(self, x):
> > >     y_h, y_l = self.g_a(x)
> > >     z_h, z_l = self.h_a((y_h, y_l))
> > >     z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
> > >     z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
> > >     gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
> > >     scales_h = gaussian_params_h
> > >     scales_l = gaussian_params_l
> > >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> > >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> > >     # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
> > >     # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
> > >     y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
> > >     y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
> > >     return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
> > >             "shape": [z_h.size()[-2:], z_l.size()[-2:]]
> > >             }
> > > 
> > > 
> > > def decompress(self, strings, shape):
> > >     assert isinstance(strings, list) and len(strings) == 2
> > >     assert isinstance(shape, list) and len(shape) == 2
> > >     z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
> > >     gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
> > >     scales_h = gaussian_params_h
> > >     scales_l = gaussian_params_l
> > >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> > >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> > >     strings_y_h, strings_y_l = strings[1]
> > >     y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
> > >     y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
> > >     x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
> > >     return {"x_hat": x_hat}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image. best wishes
> > 
> > 
> > Have you trained the compression models? I've not provided any weights, it isn't too unsurprising that the rate is higher for the compressed representation on a freshly initialized model
> 
> I trained the model with my usual customary parameters, with a learning rate of 1e-4 for VAE and 1e-5 for lambada, and more than 300 rounds of training. The dataset is (8, 128, 128) multispectral images. Incidentally the training process looks all right and the loss can be reduced to single digits, but it is the compression bitrate that gets greater than 1 when testing, I was wondering if you have encountered this problem while training.

Thank you for providing me with additional details! Something definitely doesn't seem right and is worth investigating further. 

However, as you hopefully know, I did not author the paper that introduces this compression model. I've merely implemented the model based on the description, and open sourced it.  I did not train this particular model, but a modified version that is part of ongoing work.  Still, by now, I have quite some experience in training compression models, so once I can free up some resources from ongoing experiments, I will look into it (Latest in 2 weeks).  

Since I haven't worked with multispectral images before, I'm interested in diving deeper into the topic.  If you'd like to discuss your work in more detail, you can also write me a mail (reza.furu@pm.me). If not, it would help me to tell me what dataset you've used for training/testing.

Best
Reza Furu

**Comment by fishxdx** [comment]
> > > > I'm sorry I made a mistake, the forward part works fine. The question happens when I run the compress part, here are the codes
> > > > ```
> > > > def compress(self, x):
> > > >     y_h, y_l = self.g_a(x)
> > > >     z_h, z_l = self.h_a((y_h, y_l))
> > > >     z_h_bits, z_l_bits = self.entropy_bottleneck_1.compress((z_h, z_l))
> > > >     z_h_hat, z_l_hat = self.entropy_bottleneck_1.decompress((z_h_bits, z_l_bits), (z_h.size()[-2:], z_l.size()[-2:]))
> > > >     gaussian_params_h, gaussian_params_l = self.h_s((z_h_hat, z_l_hat))
> > > >     scales_h = gaussian_params_h
> > > >     scales_l = gaussian_params_l
> > > >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> > > >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> > > >     # y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h, means=means_h)
> > > >     # y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l, means=means_l)
> > > >     y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h)
> > > >     y_l_bits = self.gaussian_conditional_l.compress(y_l, indexes_l)
> > > >     return {"strings": [[z_h_bits, z_l_bits], [y_h_bits, y_l_bits]],
> > > >             "shape": [z_h.size()[-2:], z_l.size()[-2:]]
> > > >             }
> > > > 
> > > > 
> > > > def decompress(self, strings, shape):
> > > >     assert isinstance(strings, list) and len(strings) == 2
> > > >     assert isinstance(shape, list) and len(shape) == 2
> > > >     z_hat_h, z_hat_l = self.entropy_bottleneck_1.decompress(strings[0], shape)
> > > >     gaussian_params_h, gaussian_params_l = self.h_s((z_hat_h, z_hat_l))
> > > >     scales_h = gaussian_params_h
> > > >     scales_l = gaussian_params_l
> > > >     indexes_h = self.gaussian_conditional_h.build_indexes(scales_h)
> > > >     indexes_l = self.gaussian_conditional_l.build_indexes(scales_l)
> > > >     strings_y_h, strings_y_l = strings[1]
> > > >     y_h = self.gaussian_conditional_h.decompress(strings_y_h, indexes_h)
> > > >     y_l = self.gaussian_conditional_l.decompress(strings_y_l, indexes_l)
> > > >     x_hat = self.g_s((y_h, y_l)).clamp(0, 1)
> > > >     return {"x_hat": x_hat}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > after running y_h_bits = self.gaussian_conditional_h.compress(y_h, indexes_h),y_h_bits will become bigger than the initial image. best wishes
> > > 
> > > 
> > > Have you trained the compression models? I've not provided any weights, it isn't too unsurprising that the rate is higher for the compressed representation on a freshly initialized model
> > 
> > 
> > I trained the model with my usual customary parameters, with a learning rate of 1e-4 for VAE and 1e-5 for lambada, and more than 300 rounds of training. The dataset is (8, 128, 128) multispectral images. Incidentally the training process looks all right and the loss can be reduced to single digits, but it is the compression bitrate that gets greater than 1 when testing, I was wondering if you have encountered this problem while training.
> 
> Thank you for providing me with additional details! Something definitely doesn't seem right and is worth investigating further.
> 
> However, as you hopefully know, I did not author the paper that introduces this compression model. I've merely implemented the model based on the description, and open sourced it. I did not train this particular model, but a modified version that is part of ongoing work. Still, by now, I have quite some experience in training compression models, so once I can free up some resources from ongoing experiments, I will look into it (Latest in 2 weeks).
> 
> Since I haven't worked with multispectral images before, I'm interested in diving deeper into the topic. If you'd like to discuss your work in more detail, you can also write me a mail ([reza.furu@pm.me](mailto:reza.furu@pm.me)). If not, it would help me to tell me what dataset you've used for training/testing.
> 
> Best Reza Furu
Hello Dear Sir. I am sorry to say that my dataset was created by the subject team by taking the intercepts from the satellite images and I don't have the right to share the dataset. Thank you very much for your reply and your code is very inspiring for me as well. However, time is running out and I will try the experimental results on my own again in the near future, so again I apologize if I am bothering you.
Best wishes

**Comment by 1131280642** [comment]
May I ask if you have solved this problem? I have also encountered the same situation where the calculated BPP value is too small and the PSNR value is also abnormal

**Comment by rezafuru** [comment]
> May I ask if you have solved this problem? I have also encountered the same situation where the calculated BPP value is too small and the PSNR value is also abnormal

Hi,

feel free to create a new issue, and please specify the values you're observing. Ideally, you'd include a picture of a reconstruction
